- Applications/Viqui/vqTrackingClipViewer.cxx
Fixes TrackingClips in viqui not rendering anything if there is only a single frame in the result
> Tracking clip didn't do initial render if only a single frame

- Applications/Viqui/CMakeLists.txt
- Applications/VpView/CMakeLists.txt
- Applications/VpView/vpViewCore.cxx
- CMake/coredeps.cmake
- Libraries/VgCommon/CMakeLists.txt
Fix incorrect case of GeographicLib's name in the call to find_package; the old case was partly working because GeographicLib uses the '`<lower>-config.cmake`' naming convention, but proper case for the directory name. As a result, CMake would only be able to find the package when given the full path. Using the correct case allows CMake to find GeographicLib when it is installed to a path that is searched by default (e.g. via distro packages).
Also fix an outdated use of GeographicLib's API, and switch to using imported targets to consume GeographicLib.
> Update use of GeographicLib

- CMake/coredeps.cmake
Change VXL includes to use the `_INCLUDE_DIRS` variables, rather than the `_INCLUDE_DIR` variables. The latter only include the source directory (when using VXL from a build directory, as opposed to an install directory), which results in being unable to find generated headers.
(It's not immediately clear how this would have ever worked; most likely, something in VXL changed.)
> Fix VXL include directories

- Plugins/VdfDataSources/CMakeLists.txt
- Plugins/VdfDataSources/TrackOracleArchiveSource/CMakeLists.txt
- Plugins/VdfDataSources/TrackOracleArchiveSource/track_oracle_file_format_fwd.h
- Plugins/VdfDataSources/TrackOracleArchiveSource/track_oracle_utils.h
- Plugins/VdfDataSources/TrackOracleArchiveSource/vdfTrackOracleArchiveSourcePlugin.cxx
- Plugins/VdfDataSources/TrackOracleArchiveSource/vdfTrackOracleTrackArchiveSource.cxx
- Plugins/VdfDataSources/TrackOracleArchiveSource/vdfTrackOracleTrackArchiveSource.h
- Plugins/VdfDataSources/TrackOracleArchiveSource/visgui_track_type.h
- Plugins/VspSourceService/TrackOracleArchiveSource/CMakeLists.txt
- Plugins/VspSourceService/TrackOracleArchiveSource/vsTrackOracleArchiveSourcePlugin.cxx
Port the vdfDataSources track_oracle plugin to support use of the KWIVER version of track_oracle. This makes it possible to use the plugin with the publicly available version of track_oracle (which is in KWIVER), and is an initial step in making WAMI Viewer useful without VidTK.
In theory, these changes are backwards-compatible, i.e. will still work with the old vidk track_oracle, however UUID support is presently disabled as KWIVER's track_oracle does not currently support it.
This change is analogous to the port of the vspSourceService track_oracle plugin (#6).
>  Port VDF track_oracle plugin to KWIVER

- CMakeLists.txt
Build shared libraries by default. This is necessary for plugins to work correctly due to how Qt meta-objects and dynamic casting work; otherwise, applications interacting with plugins are prone to crashing. Correspondingly, show a warning if the user has selected to build static libraries.
> Enable BUILD_SHARED_LIBS by default.

- Applications/VpView/vpVidtkActivityIO.cxx
- Applications/VpView/vpVidtkActivityIO.h
- Applications/VpView/vpVidtkEventIO.cxx
- Applications/VpView/vpVidtkEventIO.h
- Applications/VpView/vpVidtkFileEventIO.cxx
- Applications/VpView/vpVidtkFileEventIO.h
- Applications/VpView/vpVidtkFileReader.cxx
- Applications/VpView/vpVidtkFileReader.h
- Applications/VpView/vpVidtkFileTrackIO.cxx
- Applications/VpView/vpVidtkFileTrackIO.h
- Applications/VpView/vpVidtkIO.cxx
- Applications/VpView/vpVidtkIO.h
- Applications/VpView/vpVidtkReader.h
- Applications/VpView/vpVidtkTrackIO.cxx
- Applications/VpView/vpVidtkTrackIO.h
- Applications/VpView/vtkVpFileReader.cxx
- Libraries/VgVideo/vgKwaFrameMetadata.cxx
- Libraries/VgVideo/vgKwaVideoClip.cxx
- Libraries/VtkVgCore/vtkVgCoordinateTransformUtil.cxx
- Libraries/VtkVgCore/vtkVgVideoFrameMetaData.cxx
- Libraries/VtkVgQtSceneUtil/vtkVgCoordinateTransform.cxx
vcl_ methods were replaced with std:: as is necessary to build with vidtk.
> Change vcl to std:: (affects vidtk related files)

- Applications/VpView/vpFileTrackIOImpl.cxx
- Applications/VpView/vpFileTrackIOImpl.h
- Applications/VpView/vpVidtkFileTrackIO.cxx
- Applications/VpView/vpVidtkTrackIO.cxx
- Applications/VpView/vpVidtkTrackIO.h
- Libraries/VtkVgCore/vtkVgTrack.cxx
- Libraries/VtkVgCore/vtkVgTrack.h
Loading of annotated tracks, specifically those that required a .regions file with a relatively large # of interpolated states has been very inefficient, especially from the standpoint of memory usage - we have an example of a 60 MB kw18 file that consumes roughly 2 GB of memory (in track oracle) requires an additional ~6 GB to load into vivia. This was because we loaded all the states from the kw18 and then would read the regions file to remove the states loaded via kw18 that were interpolated, one at a time (this was done for a variety of reasons, but internally we need to know which state are key frames and it isn't as simple as marking with a flag) . Each time a key frame is removed, all frames between key frames are (re)computed... thus having 100 interpolated states between two key …
> Reorder track loading

- Applications/VpView/vpProjectParser.cxx
Use `try`/`catch` to detect missing values in project. This is necessary due to an upstream change that caused the method to get array values to throw an exception rather than returning `false` if the value is not present.
> Adapt to VidTK config_block API changes

- Applications/VpView/vpFseTrackIO.cxx
- Applications/VpView/vpModelIO.cxx
- Applications/VpView/vpModelIO.h
- Applications/VpView/vpProject.cxx
- Applications/VpView/vpProject.h
- Applications/VpView/vpProjectBase.h
- Applications/VpView/vpProjectParser.cxx
- Applications/VpView/vpProjectParser.h
- Applications/VpView/vpQtViewer3d.cxx
- Applications/VpView/vpTrackIO.cxx
- Applications/VpView/vpTrackIO.h
- Applications/VpView/vpVidtkTrackIO.cxx
- Applications/VpView/vpViewCore.cxx
- Applications/VpView/vpViewCore.h
- Libraries/QtVgCommon/vgColor.cxx
- Libraries/QtVgCommon/vgColor.h
- Libraries/VgCommon/vgGeoTypes.h
- Libraries/VgCommon/vgGeodesy.cxx
- Libraries/VgCommon/vgGeodesy.h
This refactors the *\<your favorite epithet here\>* out of vpProject:
- C arrays are out, C++ object types are in. This simplifies initialization, copying and validity checking.
- `std::string` and `std::map` are out, `QString` and `QHash` are in. This simplifies the new parser, and also many uses of these members, which often needed to be converted to `QString` anyway. (Using `QHash` instead of `std::map` is significantly more convenient for implementing `vpProject::IsValid`.)
- Many members are moved to a new base class, `vpProjectBase`. This class is copyable, with default copy ctor and assignment operator. `CopyConfig` is implemented using these, which *drastically* simplifies its implementation.
- Uses of `vpProject::FileState` are no longer demoted to `int`.
- Qt is used for …
> Refactor vpProject; add non-VidTK parser

- Applications/Viqui/main.cxx
- Applications/VpView/main.cxx
- Applications/VpView/vpApplication.h
- Applications/VsPlay/main.cxx
- Libraries/QtVgWidgets/vgApplication.cxx
- Libraries/QtVgWidgets/vgApplication.h
Make `vpApplication` a `vgApplication`. Modify viqui to use `vgApplication`. Add mechanism to `vgApplication` to load a user-defined "theme" (consisting of a color palette and optional widget style). Modify the main applications to use this.
This adds the ability to override the system color scheme and widget style using the new `--theme` option to specify an alternate "theme" file.
> Add "theming" support

- Plugins/VdfDataSources/TrackOracleArchiveSource/CMakeLists.txt
- Plugins/VdfDataSources/TrackOracleArchiveSource/track_oracle_utils.h
- Plugins/VdfDataSources/TrackOracleArchiveSource/vdfTrackOracleTrackArchiveSource.cxx
- Plugins/VdfDataSources/TrackOracleArchiveSource/visgui_track_type.h
- Plugins/VspSourceService/TrackOracleArchiveSource/track_oracle_utils.h
- Plugins/VspSourceService/TrackOracleArchiveSource/visgui_track_type.h
- Plugins/VspSourceService/TrackOracleArchiveSource/vsTrackOracleTrackArchiveSource.cxx
Convert the data frameworks and vspSourceService track_oracle plugins over to using track_oracle data terms for setting up their schemas, at least for the track readers. (Many of the event fields do not have data terms, so for now the event reader is unchanged.)
Also, update the data frameworks reader to use the `track_uuid` field (which exists in both VidTK and KWIVER, and seems to be actively used) rather than the `unique_id` field (which exists only in VidTK and is specific to STANAG 4676, which is not supported by KWIVER at this time.)
In addition, modify the data frameworks track_oracle plugin to also read the world location GCS from tracks. This makes it possible to read tracks that use a different GCS, rather than the hard-coded default WGS'84 lat/lon.
Note that the latter change …
> Use track_oracle data terms

- Applications/VpView/vpViewCore.cxx
- Libraries/VtkVgCore/CMakeLists.txt
- Libraries/VtkVgCore/vtkVgSGIReader.cxx
- Libraries/VtkVgCore/vtkVgSGIReader.h
Create an implementation of `vtkVgBaseImageSource` that reads [SGI image files](https://en.wikipedia.org/wiki/Silicon_Graphics_Image). Register this with WAMI Viewer.
This slightly simplified implementation does not support "dithered" color mode (3/2/2 bpp RGB) or RLE encoding, but otherwise should support just about anything one might reasonably expect to encounter.
> Add SGI reader to WAMI Viewer

- Applications/VpView/CMakeLists.txt
- Applications/VpView/vpProjectEditor.cxx
- Applications/VpView/vpProjectEditor.h
- Applications/VpView/vpProjectEditor.ui
- Applications/VpView/vpView.cxx
- Applications/VpView/vpView.ui
- Applications/VpView/vpViewCore.cxx
- Applications/VpView/vpViewCore.h
Create a rudimentary "project editor" for WAMI Viewer. Use this to allow in-application creation of a new project file, which can be immediately loaded.
>  Create WAMI Viewer project editor

- Applications/VpView/vpFseIO.cxx
- Applications/VpView/vpModelIO.cxx
- Applications/VpView/vpModelIO.h
- Applications/VpView/vpObjectInfoPanel.cxx
- Applications/VpView/vpObjectInfoPanel.ui
- Applications/VpView/vpTrackIO.cxx
- Applications/VpView/vpTrackIO.h
- Applications/VpView/vpVidtkFileIO.cxx
- Applications/VpView/vpVidtkIO.cxx
- Applications/VpView/vpVidtkTrackIO.cxx
- Applications/VpView/vpView.cxx
- Applications/VpView/vpView.h
- Applications/VpView/vpView.ui
- Applications/VpView/vpViewCore.cxx
- Applications/VpView/vpViewCore.h
- Libraries/VspUserInterface/vsScene.cxx
- Libraries/VspUserInterface/vsScenePrivate.cxx
- Libraries/VspUserInterface/vsScenePrivate.h
- Libraries/VtkVgCore/vtkVgTrack.cxx
- Libraries/VtkVgCore/vtkVgTrack.h
- Libraries/VtkVgModelView/CMakeLists.txt
- Libraries/VtkVgModelView/vtkVgTrackFilter.cxx
- Libraries/VtkVgModelView/vtkVgTrackFilter.h
- Libraries/VtkVgModelView/vtkVgTrackPVOFilter.cxx
- Libraries/VtkVgModelView/vtkVgTrackPVOFilter.h
Modify WAMI Viewer to support the use of TOC's (Track Object Classifiers, which support dynamic classifications) rather than PVO's (static classifiers that support only Person, Vehicle, Other).
> Implement TOC support in WAMI Viewer

- Applications/VpView/CMakeLists.txt
- Applications/VpView/vpVdfIO.cxx
- Applications/VpView/vpVdfIO.h
- Applications/VpView/vpVdfTrackIO.cxx
- Applications/VpView/vpVdfTrackIO.h
- Applications/VpView/vpViewCore.cxx
- Applications/VpView/vpViewCore.h
Create an I/O implementation for WAMI Viewer that uses exclusively the data frameworks (`vdfSourceService`) and does not depend on VidTK in any fashion. (`vpVidtkFileReader` also uses `vdfSourceService`, but had a fallback to VidTK's track reader process, and the retrieved tracks were first wrapped in VidTK tracks; this new implementation cuts out that step.) For now, only initial track reading is supported. Events, activities, and importing are not supported.
This implementation also does not support the various ancillary files that have sprouted up, but that is probably The Right Thing To Do anyway; if we continue to support such things, they should be handled at the reader plugin level, rather than partly at the application level, as is being done currently.
This should make it …
>  Implement non-VidTK track reader for WAMI Viewer

- Applications/VpView/CMakeLists.txt
- Applications/VpView/vpKwiverEmbeddedPipelineWorker.cxx
- Applications/VpView/vpKwiverEmbeddedPipelineWorker.h
- Applications/VpView/vpView.cxx
- Applications/VpView/vpView.h
- Applications/VpView/vpView.ui
- Applications/VpView/vpViewCore.cxx
- Applications/VpView/vpViewCore.h
- Libraries/VtkVgModelView/vtkVgTrackInfo.h
This adds the ability to run KWIVER pipelines from within WAMI viewer. Pipelines can consume imagery and can consume and/or produce tracks.
> Add support for KWIVER embedded pipelines to WAMI Viewer

- Applications/VpView/vpImageSourceFactory.h
- Applications/VpView/vpViewCore.cxx
- Libraries/VtkVgCore/vtkVgBaseImageSource.cxx
- Libraries/VtkVgCore/vtkVgBaseImageSource.h
- Libraries/VtkVgCore/vtkVgImageSource.cxx
- Libraries/VtkVgCore/vtkVgImageSource.h
- Libraries/VtkVgCore/vtkVgJPEGReader.cxx
- Libraries/VtkVgCore/vtkVgJPEGReader.h
- Libraries/VtkVgCore/vtkVgMultiResJpgImageReader2.cxx
- Libraries/VtkVgCore/vtkVgMultiResJpgImageReader2.h
- Libraries/VtkVgCore/vtkVgPNGReader.cxx
- Libraries/VtkVgCore/vtkVgPNGReader.h
- Libraries/VtkVgCore/vtkVgSGIReader.cxx
- Libraries/VtkVgCore/vtkVgSGIReader.h
- Libraries/VtkVgIO/vtkVgGDALReader.cxx
- Libraries/VtkVgIO/vtkVgGDALReader.h
Get rid of superfluous `RegisterVpImageSource` "helper" class. Add `const` to some methods of `vtkVgBaseImageSource` that really have no excuse for *not* being `const`. Don't store time stamp in `vtkVgBaseImageSource`.
> Clean up some WAMI Viewer image reading stuff

- Applications/VpView/vpKwiverEmbeddedPipelineWorker.cxx
- Applications/VpView/vpKwiverImproveTrackWorker.cxx
- Applications/VpView/vpViewCore.cxx
Fix inconsistency in default track type colors (see commit message for details). Adapt to KWIVER upstream renaming `time_us_t` to `time_usec_t`.
> Minor fixes

- Libraries/VtkVgCore/vtkVgPlotTimeline.cxx
This fixes an compile error discovered when building with VS15 (2017).
> Fixes compile error when building with VS15(2017)

- Libraries/VspData/vsEventInfo.cxx
- Libraries/VvVtkWidgets/vvEventInfo.cxx
- Libraries/VvWidgets/vvDescriptorStyleSetting.cxx
- Libraries/VvWidgets/vvScoreGradientSetting.cxx
Rename use of `qtScopedSettingGroup` → `qtScopedSettingsGroup` per upstream change, and refactor uses to use the recently added `with_expr`.
> Adapt to qtScopedSettingGroup rename

- Applications/VpView/vpKwiverEmbeddedPipelineWorker.cxx
- Applications/VpView/vpKwiverEmbeddedPipelineWorker.h
- Applications/VpView/vpViewCore.cxx
Tweak WAMI Viewer's embedded pipeline support to also supply the TOC to tracks being passed as input to the embedded pipeline.
> Set TOC's on input tracks to embedded pipeline

- Applications/VpView/vpFileDataSource.cxx
- Applications/VpView/vpFileDataSource.h
- Applications/VpView/vpFrameMap.cxx
- Applications/VpView/vpFrameMap.h
- Applications/VpView/vpKwiverEmbeddedPipelineWorker.cxx
- Applications/VpView/vpKwiverVideoSource.cxx
- Applications/VpView/vpQtViewer3d.cxx
- Applications/VpView/vpViewCore.cxx
- Applications/VpView/vpViewCore.h
Rewrite the internal logic of vpFileDataSource using Qt, rather than a mix of STL, VTK and kwsys, and refactor the API to use Qt conventions. Overhaul vpFrameMap, making use of Qt data types. Refactor users as needed.
This produces a cleaner and more consistent implementation, and will make some future work easier.
> Refactor WAMI Viewer frame source classes

- Applications/VpView/vpViewCore.cxx
An image shift is necessary so that the upper left is treated as the origin
if input images do not all have the same height. The logic doing the shift
was incorrectly doing a shift when the input images had the same height but
zooming in (or translating) had caused the reader (vtkVgGDALReader) to only
return a subset of the image.
> Use full image dimensions when determining need for Y offset

- Libraries/VtkVgCore/vtkVgPlotTimeline.cxx
- Plugins/VvQueryService/KipQueryService/vvKipQuerySession.cxx
This PR includes fixes to the `viame/master` branch for it to compile on Windows, specifically with Visual Studio 15. Perhaps some of this is also relevant for `master`.
These are largely straightforward changes, but I have a couple concerns:
- What's the canonical place in a `CMakeLists.txt` file to call `add_compile_options`?
- `KipQueryService` requires C++17 because of one use of `[[maybe_unused]]`. Is it worth bumping up the required standard for this?
@mwoehlke-kitware @mattdawkins
> Windows fixes (VIAME)

- Applications/VpView/vpViewCore.cxx
Kwiver recently changed to disallow direct access to the object_track_state's detection object. This PR changes those calls to use the function detection() to fetch it.
> Use the function to get a detection

- CMake/coredeps.cmake
- Libraries/VtkVgCore/vtkVgChartTimeline.cxx
Remove requirement for `boost::signals`; this library hasn't existed for some time, and does not appear to be in use. Fix an error using `boost::posix_time::seconds`; we were trying to pass a double to this, but only integral types are supported.
> Fix boost errors

- Applications/VpView/CMakeLists.txt
The `kwiver::sprokit_tools` library was removed from KWIVER. I'm not sure why we were linking this originally, but `sprokit_pipeline` seems sufficient; link to that instead.
> Fix sprokit link error

- Applications/VsPlay/Plugins/vsVvqsDatabaseSource.cxx
- CMake/config.cmake
- Libraries/QtVgCommon/vgGeoUtil.cxx
- Libraries/VvVtkWidgets/vvVideoQueryDialogPrivate.cxx
- Libraries/VvWidgets/vvDescriptorInfoWidget.cxx
- Libraries/VvWidgets/vvTrackInfoWidget.cxx
Due to the combined quirkiness of how VS processes string literals and how [QStringLiteral](https://doc.qt.io/qt-5/qstring.html#QStringLiteral) (or more specifically, [QT_UNICODE_LITERAL](/qt/qtbase/blob/287ace562ee5ddff22f7dbf4e49ae5f0520f2308/src/corelib/text/qstringliteral.h#L63)) is implemented, Visual Studio clobbers characters that are outside the local code page in certain uses of QStringLiteral. This happens because QT_UNICODE_LITERAL does not actually force the literal to be UTF-16, but rather prepends it with a UTF-16 literal, relying on concatenation promotion to make the remaining string also UTF-16. However, by the time that happens, Visual Studio has already corrupted the literal data.
The work-around is to prefix the actual literal (i.e. `u"foo"` instead of `"foo"` inside …
> Fix Unicode string literals on MSVC

- CMakeLists.txt
- Libraries/VvVtkWidgets/CMakeLists.txt
Fix a build breakage that was introduced by 5fe5f442c741, due to the location of uic-generated headers changing with the switch from manual use of qtX_wrap_ui to AUTOUIC. This happened because, unfortunately, we have "private" headers that are used by subclasses across a library boundary that necessitate that the UI headers are also externally visible.
Reviews by @mathstuf and/or @dstoup would also be appreciated.
> Fix installation of AUTOUIC headers

- Applications/VpView/vpKwiverEmbeddedPipelineWorker.cxx
When activity_type was added to kwiver, cooler heads realized the duplication of code and made the generic class_map to satisfy detected_object and activity.
@mwoehlke-kitware  @RustyBlue
> Kwiver recently discarded detected_object_type

- Applications/VpView/vpKwiverEmbeddedPipelineWorker.cxx
Revert commit 9a4b54076e3d588f2dcbec3ad0777e6e8d06ad51. The upstream (KWIVER) changes caused issues due to conflation of detected object and activity types, due to which `class_map` was refactored to be a base class, and the original `detected_object_type` was reintroduced. Since this means that consumers do not need to be modified, revert the prior changes.
@dstoup, PTAL; thanks!
> Revert "Kwiver recently discarded detected_object_type (#69)"
